# Generated by Django 3.2.9 on 2021-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='amazon.com', max_length=25500)),
            ],
        ),
        migrations.DeleteModel(
            name='ReatUrl',
        ),
    ]
