# Generated by Django 3.2.9 on 2021-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211209_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reacturl',
            name='url',
            field=models.URLField(default='https://www.amazon.com/Lenovo-Chromebook-11-6-Inch-Processor-82HG0006US/dp/B08T6N424Z/ref=sr_1_1?qid=1639055127&s=computers-intl-ship&sr=1-1', max_length=25500),
        ),
    ]
